# Generated by Django 6.0.3 on 2026-03-19 14:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_link', models.CharField(blank=True, null=True)),
                ('created_by', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_clerk_id', models.CharField()),
            ],
            options={
                'verbose_name_plural': 'posts',
            },
        ),
    ]
