# Generated by Django 6.0.3 on 2026-03-24 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_comments_post_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'posts'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
